### ISSUE TITLE
Add Support for `io.vertx:vertx-core:4.3.5`

### ISSUE THREAD

**Issue by linghengqian** [oracle/graalvm-reachability-metadata#117]
**Is your feature request related to a problem? Please describe.**

- Yes, refer to https://github.com/netty/netty/issues/11369 , https://github.com/apache/shardingsphere/issues/21347 and https://github.com/eclipse-vertx/vert.x/issues/3960 .

**Describe the solution you'd like**

- Add Support for `io.vertx:vertx-core:4.3.5`.

**Describe alternatives you've considered**

- Null.

**Additional context**

- Metadata generated at https://github.com/linghengqian/graalvm-trace-metadata-smoketest/issues/1 .

**Comment by linghengqian** [comment]
- I am working on this issue.

**Comment by linghengqian** [comment]
- I know that vertx-core itself has GraalVM reachability metadata, but I really don't understand a series of errors around `io.vertx.core.Vertx#clusteredVertx(VertxOptions options, Handler<AsyncResult<Vertx>> resultHandler)` . I would first investigate https://github.com/oracle/graalvm-reachability-metadata/issues/32.
```shell
11月 21, 2022 7:41:36 下午 io.vertx.core.impl.launcher.commands.RunCommand
严重: Failed to load or instantiate the isolated deployer
java.lang.ClassNotFoundException: io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
        at java.base@17.0.5/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:52)
11月 21, 2022 7:41:36 下午 com.hazelcast.config.XmlConfigBuilder
严重: Failed to parse the inputstream
Exception: Stream closed
11月 21, 2022 7:41:36 下午 io.vertx.core.impl.VertxImpl
严重: Failed to initialize clustered Vert.x
com.hazelcast.config.InvalidConfigurationException: Stream closed
        at com.hazelcast.config.XmlConfigBuilder.parse(XmlConfigBuilder.java:213)
Caused by: java.io.IOException: Stream closed
        at java.base@17.0.5/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:157)
11月 21, 2022 7:41:36 下午 com.hazelcast.config.XmlConfigBuilder
严重: Failed to parse the inputstream
Exception: Stream closed
11月 21, 2022 7:41:36 下午 io.vertx.core.impl.VertxImpl
严重: Failed to initialize clustered Vert.x
com.hazelcast.config.InvalidConfigurationException: Stream closed
        at com.hazelcast.config.XmlConfigBuilder.parse(XmlConfigBuilder.java:213)
Caused by: java.io.IOException: Stream closed
        at java.base@17.0.5/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:157)
11月 21, 2022 7:41:36 下午 io.vertx.core.impl.VertxImpl
严重: Failed to leave cluster
java.lang.NullPointerException
        at io.vertx.spi.cluster.hazelcast.HazelcastClusterManager.lambda$leave$5(HazelcastClusterManager.java:243)
com.hazelcast.config.InvalidConfigurationException: Stream closed
        at com.hazelcast.config.XmlConfigBuilder.parse(XmlConfigBuilder.java:213)
Caused by: java.io.IOException: Stream closed
        at java.base@17.0.5/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:157)
com.hazelcast.config.InvalidConfigurationException: Stream closed
        at com.hazelcast.config.XmlConfigBuilder.parse(XmlConfigBuilder.java:213)
Caused by: java.io.IOException: Stream closed
        at java.base@17.0.5/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:157)
```

**Comment by linghengqian** [comment]
- I think I solved the problem above.
- ![image](https://user-images.githubusercontent.com/20187731/203056822-36fba1da-c1d8-44e8-a839-9ed41a0adec5.png)

**Comment by linghengqian** [comment]
- I noticed that vertx-core doesn't seem to need GraalVM reachability metadata to run nativeTest properly. From this point of view, I don't see the need to add support for vertx-core . Unless a friend gives an example of a failed nativeTest.
