### ISSUE TITLE
Reachability metadata for hibernate-orm does not cover reflection in org.hibernate.dialect.PostgreSQLPGObjectJdbcType

### ISSUE THREAD

**Issue by wilkinsona** [oracle/graalvm-reachability-metadata#131]
**Describe the bug**
When using Postgres, Hibernate logs a warnings due to some reflection failing.

**To Reproduce**

https://github.com/spring-projects/spring-boot/issues/33400 contains a link to a sample that reproduces the problem.

**Expected behavior**
Hibernate can bootstrap itself without warnings.

**Logs**

```
2022-11-28T10:14:33.953-05:00  WARN 62921 --- [           main] o.h.dialect.PostgreSQLPGObjectJdbcType   : PostgreSQL JDBC driver classes are inaccessible and thus, certain DDL types like JSONB, JSON, GEOMETRY can not be used!

java.lang.NoSuchMethodException: org.postgresql.util.PGobject.<init>()
        at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585) ~[chapter-4-spring-data-jpa:na]
        at java.base@17.0.5/java.lang.Class.getConstructor(DynamicHub.java:2271) ~[chapter-4-spring-data-jpa:na]
        at org.hibernate.dialect.PostgreSQLPGObjectJdbcType.<clinit>(PostgreSQLPGObjectJdbcType.java:50) ~[chapter-4-spring-data-jpa:6.1.5.Final]
        at org.hibernate.dialect.PostgreSQLDialect.registerColumnTypes(PostgreSQLDialect.java:231) ~[chapter-4-spring-data-jpa:6.1.5.Final]
        at org.hibernate.dialect.Dialect.contributeTypes(Dialect.java:1341) ~[chapter-4-spring-data-jpa:6.1.5.Final]
        at org.hibernate.dialect.PostgreSQLDialect.contributeTypes(PostgreSQLDialect.java:1229) ~[chapter-4-spring-data-jpa:6.1.5.Final]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:386) ~[na:na]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:143) ~[na:na]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1350) ~[chapter-4-spring-data-jpa:6.1.5.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1421) ~[chapter-4-spring-data-jpa:6.1.5.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66) ~[na:na]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[chapter-4-spring-data-jpa:6.0.2]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[chapter-4-spring-data-jpa:3.0.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[chapter-4-spring-data-jpa:3.0.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[chapter-4-spring-data-jpa:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[chapter-4-spring-data-jpa:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[chapter-4-spring-data-jpa:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[chapter-4-spring-data-jpa:3.0.0]
        at org.acme.Chapter4SpringDataJpaApplication.main(Chapter4SpringDataJpaApplication.java:10) ~[chapter-4-spring-data-jpa:na]
```

**System Info (please complete the following information):**
 - Graal 22.3

**Comment by itineric** [comment]
This is not working anymore with hibernate-core 6.2+
The reflect-config.json found in reachable metadata misses the part about PGobject.

Found for 6.1.1-Final

```
{
    "condition": {
      "typeReachable": "org.postgresql.Driver"
    },
    "name": "org.postgresql.util.PGobject",
    "queryAllDeclaredMethods": true,
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  },
```

missing for 6.2.0.Final

**Comment by msupic** [comment]
@itineric - PGobject is initialized in the [PostgreSQLPGObjectJdbcType](https://github.com/hibernate/hibernate-orm/blob/6.1.7/hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLPGObjectJdbcType.java) class in hibernate 6.1.7. That class doesn't exit in hibernate 6.2.0 ([dialect directory](https://github.com/hibernate/hibernate-orm/tree/6.2.0/hibernate-core/src/main/java/org/hibernate/dialect)). If you are still using hibernate 6.1.7, you need to use metadata for 6.1.7 instead of metadata for 6.2.0

**Comment by itineric** [comment]
I am getting the following log during `add-reachability-metadata`

```
[graalvm reachability metadata repository for org.hibernate.orm:hibernate-core:6.1.7.Final]: Configuration directory not found. Trying latest version.
[graalvm reachability metadata repository for org.hibernate.orm:hibernate-core:6.1.7.Final]: Configuration directory is org.hibernate.orm/hibernate-core/6.2.0.Final
```

And I cannot find the metadata you are talking about, am I looking at the wrong place ? https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/org.hibernate.orm/hibernate-core

**Comment by msupic** [comment]
Sorry, I replaced `6.1.1.Final` with `6.1.7.Final` but the point is the same, PGobject is initialized in the PostgreSQLPGObjectJdbcType class in `6.1.1.Final` and not in `6.2.0.Final`, so if you are using hibernate from `6.1.x` series, you need to continue using `6.1.1.Final` metadata. There is a ticket for native plugins to not always use the latest version metadata: https://github.com/graalvm/native-build-tools/issues/430. Until that is done, you can explicitly set metadata version: https://github.com/oracle/graalvm-reachability-metadata/issues/273#issuecomment-1517174789

**Comment by itineric** [comment]
Thanks, I figured it out, its working with the workaround
