### ISSUE TITLE
Add io.rsocket metadata

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graalvm-reachability-metadata#14]
Used version:

```
|    +--- io.rsocket:rsocket-core:1.1.2 (c)
|    +--- io.rsocket:rsocket-transport-netty:1.1.2 (c)
```

Our sample fails with:

```
java.lang.NoClassDefFoundError: Could not initialize class io.rsocket.internal.jctools.queues.MpscUnboundedArrayQueue
	at io.rsocket.internal.UnboundedProcessor.<init>(UnboundedProcessor.java:102) ~[rsocket:na]
	at io.rsocket.internal.UnboundedProcessor.<init>(UnboundedProcessor.java:97) ~[rsocket:na]
	at io.rsocket.internal.BaseDuplexConnection.<init>(BaseDuplexConnection.java:27) ~[rsocket:na]
	at io.rsocket.transport.netty.TcpDuplexConnection.<init>(TcpDuplexConnection.java:41) ~[na:na]
	at io.rsocket.transport.netty.server.TcpServerTransport.lambda$start$0(TcpServerTransport.java:116) ~[na:na]
	at reactor.netty.transport.ServerTransportConfig$ServerTransportDoOnConnection.onStateChange(ServerTransportConfig.java:253) ~[na:na]
	at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:478) ~[na:na]
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:62) ~[na:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230) ~[rsocket:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216) ~[rsocket:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209) ~[rsocket:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398) ~[na:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230) ~[rsocket:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216) ~[rsocket:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895) ~[rsocket:4.1.79.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:522) ~[rsocket:4.1.79.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[rsocket:4.1.79.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[na:na]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[rsocket:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[rsocket:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[rsocket:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[na:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[na:na]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
	at java.lang.Thread.run(Thread.java:833) ~[rsocket:na]
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704) ~[rsocket:na]
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
```

**Comment by sdeleuze** [comment]
We potentially need to copy and adap Netty native config to cover the shaded one provided with RSocket.

**Comment by sdeleuze** [comment]
Those hints are now provided directly by RSocket JAR so you can close this issue as not planned / won't fix.

**Comment by sureshg** [comment]
@sdeleuze would it work for rsocket-kotlin also? When I tried a few days back, I was getting some wiered error for `rsocket-kotlin` (coming from `ktor` client dependency)

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.ktor.client.engine.cio.CIOEngine.<init>(io.ktor.client.engine.cio.CIOEngineConfig)
Parsing context:
   at io.ktor.client.engine.cio.CIOEngine.<init>(CIOEngine.kt)
   at io.ktor.client.engine.cio.CIO.create(CIOCommon.kt:35)
   at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
   ....
   Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Discovered a type for which getDeclaringClass0 cannot be called: io.ktor.util.CoroutinesUtilsKt$SilentSupervisor$$inlined$CoroutineExceptionHandler$1. This error is reported at image build time because class io.ktor.util.CoroutinesUtilsKt$SilentSupervisor$$inlined$CoroutineExceptionHandler$1 is registered for linking at image build time by command line
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SVMHost.handleLinkageError(SVMHost.java:426)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SVMHost.getDeclaringClass(SVMHost.java:412)
	......
Caused by: java.lang.IncompatibleClassChangeError: io.ktor.util.CoroutinesUtilsKt and io.ktor.util.CoroutinesUtilsKt$SilentSupervisor$$inlined$CoroutineExceptionHandler$1 disagree on InnerClasses attribute
	at java.base/java.lang.Class.getDeclaringClass0(Native Method)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor$NativeAccessor.invoke0(Native Method)
```

**Comment by sdeleuze** [comment]
As far as I know, recent versions of `rsocket-kotlin` are based on a different Kotlin multiplatform implementation, so no those matadata should not cover it. Also the error looks like Ktor specific.

**Comment by sureshg** [comment]
@sdeleuze jfyi: this is fixed in the latest GraalVM CE dev (java 19) release. My app is working fine now.
