### ISSUE TITLE
add support for jOOQ

### ISSUE THREAD

**Issue by ceyhunn** [oracle/graalvm-reachability-metadata#155]
**Is your feature request related to a problem? Please describe.**
I successfully build and run spring boot native app, but I can't fetch data with jooq from postgresql. It shows following error:

```
java.lang.NullPointerException: null
        at org.jooq.impl.DefaultBinding.binding(DefaultBinding.java:471) 
        at org.jooq.impl.DefaultBinding.binding(DefaultBinding.java:315)
        at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:387)
        at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:335)
        at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:331)
        at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:319)
        at org.jooq.impl.ArrayDataType.<init>(ArrayDataType.java:63)
        at org.jooq.impl.AbstractDataType.getArrayDataType(AbstractDataType.java:611)
        at org.jooq.impl.DefaultDataType.getArrayDataType(DefaultDataType.java:136)
        at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:392)
        at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:335) 
        at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:331)
        at org.jooq.impl.DefaultDataType.<init>(DefaultDataType.java:315)
        at org.jooq.impl.BuiltInDataType.<init>(BuiltInDataType.java:60)
        at org.jooq.impl.SQLDataType.<clinit>(SQLDataType.java:316)
        at com.example.is.jooq.tables....
        at com.example.is.jooq.tables....
        at com.example.is.jooq.tables....
        at com.example.is.jooq.tables....
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) 
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) 
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) 
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) 
......
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[https://github.com/jOOQ/jOOQ/issues/8779](https://github.com/jOOQ/jOOQ/issues/8779)

**Comment by lbkulinski** [comment]
Have there been any updates on this? It’s something I’d like to see as well. Thanks!

**Comment by sdeleuze** [comment]
If some support for jOOQ is provided here, I teng to think it should be not tied to Spring Boot starter which is just a way to get all the required dependencies, I updated the title of the issue accordingly.

I also commented on jOOQ side to ask if the project lead want to provide builtin support or if it should happen here.

**Comment by lukaseder** [comment]
I am regretting this already, see this comment and follow up comments: https://github.com/jOOQ/jOOQ/issues/8779#issuecomment-1415790292

**Comment by linghengqian** [comment]
- @msupic  https://github.com/oracle/graalvm-reachability-metadata/pull/257 has resolved this issue, I think this issue should not be kept open. 
- If anyone finds missing metadata, they should open a new issue with the corresponding minimal reproducible example.
