### ISSUE TITLE
Support for com.baomidou:mybatis-plus-boot-starter:3.5.3.1

### ISSUE THREAD

**Issue by fushun1990** [oracle/graalvm-reachability-metadata#159]
**Describe the problem**
`
Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
        org.apache.ibatis.builder.CacheRefResolver
        org.apache.ibatis.parsing.XNode
        org.apache.ibatis.builder.annotation.MethodResolver
        org.apache.ibatis.builder.ResultMapResolver
        org.apache.ibatis.mapping.ResultFlag

        at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:87)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor$ConfigurationPropertiesReflectionHintsContribution.applyTo(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:70)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
`

**Additional context**

**System Info (please complete the following information):**
 - OS: [e.g. `mac`]
 - GraalVM Version [e.g. `graalvm-ce-java17-22.3.0`]
 - Java Version [e.g. `17`]
 - Plugin version [e.g. `native-maven-plugin:0.9.19`]

**To Reproduce**
[demo 2.zip](https://github.com/oracle/graalvm-reachability-metadata/files/10347124/demo.2.zip)

**Comment by wilkinsona** [comment]
I don't think this can be fixed with reachability metadata. The problem will need to be addressed in the code that's attempting to bind configuration properties directly to ibatis classes. Presumably that code is part of mybatis-plus-boot-starter.

**Comment by sdeleuze** [comment]
@dnestoro I think you can close this issue.

**Comment by fushun1990** [comment]
ok，
但是能否给我一些意见，我应该怎么进行修改才可以解决这个问题了。或者是否有相似问题的解决方案我做参考。
我没有找到相关是学习文档和解决方案。谢谢！！

以上文字是中文翻译的。抱歉

ok
But could you please give me some advice on how I should modify to solve this problem? Or whether there are solutions to similar problems for my reference.
I did not find the relevant documentation and solution. Thank you!!

The above text is translated from Chinese. Sorry

**Comment by linghengqian** [comment]
@fushun1990 

- What kind of help do you need? Do you want to attend GraalVM's offline meetings? None of these questions are relevant to the current issue. 

- Normally you just need to create a Gradle project and write unit tests for Mybatis Plus using GraalVM Native Build Tools Gradle Plugin. You can then collect GraalVM accessibility metadata by executing Gradle tasks and manually adjust and execute nativeTest. 

- You major need to read the https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md and https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html .

**Comment by vjovanov** [comment]
Human intervention needed

The automated job failed for `com.baomidou:mybatis-plus-boot-starter:jar`.

Preserved work branch: https://github.com/oracle/graalvm-reachability-metadata/tree/ai%2Fvjovanov%2Fhuman-intervention%2Fissue-159-library-new-request-com.baomidou-mybatis-plus-boot-starter-jar-9fdc0fb6

The most likely failing stage was artifact discovery feeding test generation. In `logs/com.baomidou:mybatis-plus-boot-starter:jar/discover-artifact-metadata/discover_artifact_metadata.log` (also mirrored in `build/agent-artifact-discovery-logs/com.baomidou-mybatis-plus-boot-starter-jar.log`), the run was asked to resolve the exact version `jar` for `com.baomidou:mybatis-plus-boot-starter`. Maven metadata shows only normal numeric versions for this artifact, and the attempted fetch for `.../mybatis-plus-boot-starter/jar/mybatis-plus-boot-starter-jar.pom` returned HTTP 404 `NoSuchKey`. The generated discovery output in `build/discovered-artifact-metadata/com.baomidou-mybatis-plus-boot-starter-jar.json` therefore fell back to `N/A` for `source-code-url`, `test-code-url`, and `documentation-url`.

There is no generated `tests/src/com.baomidou/mybatis-plus-boot-starter/...`, `metadata/com.baomidou/mybatis-plus-boot-starter/...`, or `stats/com.baomidou/mybatis-plus-boot-starter/...` output in the preserved worktree, and no matching run metrics entry was recorded for this coordinate. That points to a bad coordinate/version input (`jar` being treated as the version) rather than a library-specific metadata or native-image test failure.

Suggested manual next steps:
1. Re-run the new-library flow with the correct full coordinates including a real version, not `:jar` as the version.
2. Check the issue/pipeline input parsing so packaging/classifier is not being written into the version field for `library-new-request`.
3. After correcting the coordinates, regenerate discovery/test artifacts and verify `build/discovered-artifact-metadata/com.baomidou-mybatis-plus-boot-starter-jar.json` no longer contains `N/A` placeholders.

**Comment by vjovanov** [comment]
Human intervention needed

The automated job failed for `com.baomidou:mybatis-plus-boot-starter:3.5.3.1`. Preserved work is available here: https://github.com/oracle/graalvm-reachability-metadata/tree/ai%2Fvjovanov%2Fhuman-intervention%2Fissue-159-library-new-request-com.baomidou-mybatis-plus-boot-starter-3.5.3.1-17c6c992. That preserved commit contains the generated test changes, but the actionable failure appears to be later in metadata fix / `nativeTest`, not in initial test generation.

Most likely failing stage: native-image metadata resolution. In `human-intervention-logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-05-07T03-31-00-918106Z.log`, the native image builds and 6 tests run, but 4 native tests fail with `ClassNotFoundException: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$PooledDataSourceCondition`, and `propertiesResolveMapperLocationsAndCanBeCustomized()` still fails with `org.apache.ibatis.logging.LogException` caused by a `NullPointerException`. Earlier reruns in `human-intervention-logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-05-07T03-00-09-610906Z.log` and `human-intervention-logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-05-07T03-07-58-979245Z.log` show the same area moving from `NoSuchMethodException: org.springframework.context.annotation.ConfigurationClassPostProcessor.<init>()` to the remaining Spring condition-class and MyBatis logging gaps. `human-intervention-logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/metadata-fix/codex.log` shows the metadata-fix attempt was still iterating on Spring Boot condition/resource registration and MyBatis logging reachability when the run ended. Metrics also ended in failure (`stats/com.baomidou/mybatis-plus-boot-starter/3.5.3.1/execution-metrics.json`: status `failure`, 4 iterations, 331 generated LOC), so dynamic-access coverage was not produced.

Please inspect:
- `human-intervention-logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-05-07T03-31-00-918106Z.log`
- `human-intervention-logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-05-07T03-07-58-979245Z.log`
- `human-intervention-logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/metadata-fix/codex.log`
- `human-intervention-logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/post-gen/pi-post-gen-2026-05-07T03-29-23-058385Z.log`

Next steps:
1. Continue from the preserved branch and finish the reachability metadata for Spring Boot auto-configuration condition classes/resources and the MyBatis logging constructors used at native runtime.
2. Re-run `./gradlew test -Pcoordinates=com.baomidou:mybatis-plus-boot-starter:3.5.3.1` to confirm the 4 native failures clear.
3. If native tests pass, rerun metrics/coverage collection and update the follow-up with the resulting dynamic-access coverage.

**Comment by vjovanov** [comment]
Human intervention needed

The automated job failed for `com.baomidou:mybatis-plus-boot-starter:3.5.3.1`.

Preserved work branch: https://github.com/oracle/graalvm-reachability-metadata/tree/ai%2Fvjovanov%2Fhuman-intervention%2Fissue-159-library-new-request-com.baomidou-mybatis-plus-boot-starter-3.5.3.1-14140111

Most likely failing stage: generated test validation during native test execution. The preserved branch contains generated test commits, but `stats/com.baomidou/mybatis-plus-boot-starter/3.5.3.1/execution-metrics.json` still reports `status: failure`, `generated_loc: 0`, `metadata_entries: 0`, and no test/metadata artifacts, and there is no `stats/com.baomidou/mybatis-plus-boot-starter/3.5.3.1/stats.json`, so dynamic-access coverage is unavailable. In the earlier native runs (`logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-06-07T08-51-18-579421Z.log` and `logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-06-07T08-51-53-351190Z.log`), all generated tests failed because Spring Boot could not open `com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class` inside the native image. After post-gen trimmed several off-target tests (`logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/post-gen/pi-post-gen-2026-06-07T09-12-35-751571Z.log`), the final native run still failed in `propertiesResolveMapperLocationsAndRetainFluentCustomizations()` with `IllegalStateException: Cannot enable lazy loading because Javassist is not available`, caused by `ClassNotFoundException: org.apache.ibatis.javassist.util.proxy.ProxyFactory` (`logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-06-07T09-15-36-074359Z.log` and `tests/src/com.baomidou/mybatis-plus-boot-starter/3.5.3.1/test-results-native/test/TEST-junit-jupiter.xml`). This looks like an incorrect or non-native-friendly generated test path plus unfinished Spring/MyBatis metadata follow-up, not a ready-to-merge new-library support change.

Please inspect:
- `logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/add-new-library-support/pi-generation-2026-06-07T08-49-12-412891Z.log`
- `logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/post-gen/pi-post-gen-2026-06-07T09-12-35-751571Z.log`
- `logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/metadata-fix/codex.log`
- `logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-06-07T08-51-53-351190Z.log`
- `logs/com.baomidou:mybatis-plus-boot-starter:3.5.3.1/gradle-test/gradle-test-2026-06-07T09-15-36-074359Z.log`
- `stats/com.baomidou/mybatis-plus-boot-starter/3.5.3.1/execution-metrics.json`
- `tests/src/com.baomidou/mybatis-plus-boot-starter/3.5.3.1/test-results-native/test/TEST-junit-jupiter.xml`

Next steps:
1. Review the preserved branch test additions in `tests/src/com.baomidou/mybatis-plus-boot-starter/3.5.3.1/src/test/java/com_baomidou/mybatis_plus_boot_starter/Mybatis_plus_boot_starterTest.java` and remove or rewrite the `MybatisConfiguration`-based assertion path so the test only exercises native-friendly starter behavior.
2. If that path is intended, add the missing Spring/MyBatis reachability support for the auto-configuration class resource and the MyBatis/Javassist proxy path, then rerun the library test.
3. Re-run `./gradlew test -Pcoordinates=com.baomidou:mybatis-plus-boot-starter:3.5.3.1` after the test/metadata adjustment and regenerate stats if the native run passes.
