### ISSUE TITLE
Add jakarta.mail metadata

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graalvm-reachability-metadata#18]
Our `mail` smoketest fails because metadata for `com.sun.mail:jakarta.mail:2.0.1` is missing:

```
Caused by: org.springframework.mail.MailSendException: Mail server connection failed. Failed messages: jakarta.mail.NoSuchProviderException: smtp
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448) ~[mail:6.0.0-SNAPSHOT]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:323) ~[mail:6.0.0-SNAPSHOT]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:312) ~[mail:6.0.0-SNAPSHOT]
	at com.example.mail.CLR.run(CLR.java:23) ~[mail:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) ~[mail:3.0.0-SNAPSHOT]
	... 5 common frames omitted
Caused by: jakarta.mail.NoSuchProviderException: smtp
	at jakarta.mail.Session.getService(Session.java:856) ~[na:na]
	at jakarta.mail.Session.getTransport(Session.java:772) ~[na:na]
	at jakarta.mail.Session.getTransport(Session.java:713) ~[na:na]
	at jakarta.mail.Session.getTransport(Session.java:693) ~[na:na]
	at org.springframework.mail.javamail.JavaMailSenderImpl.getTransport(JavaMailSenderImpl.java:538) ~[mail:6.0.0-SNAPSHOT]
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:517) ~[mail:6.0.0-SNAPSHOT]
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437) ~[mail:6.0.0-SNAPSHOT]
	... 9 common frames omitted
```

**Comment by sdeleuze** [comment]
I will take that one.
