### ISSUE TITLE
Spring native with liquibase is not working

### ISSUE THREAD

**Issue by prabuanandan** [oracle/graalvm-reachability-metadata#239]
**Describe the problem**
The spring native application using spring boot 3 + liquibase is not working as expected 

**Additional context**

**System Info (please complete the following information):**
 - OS: [Mac]
 - GraalVM Version [GraalVM CE 22.3.1]
 - Java Version [19]
 <native.maven.plugin.version>0.9.19</native.maven.plugin.version>

This is the maven config 
```
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <buildpacks>
                            <buildpack>gcr.io/paketo-buildpacks/graalvm</buildpack>
                            <buildpack>gcr.io/paketo-buildpacks/java-native-image</buildpack>
                        </buildpacks>
                        <env>
                            <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
                            <BP_JVM_VERSION>19.0.2</BP_JVM_VERSION>
                        </env>
                    </image>
                </configuration>
                <executions>
                    <execution>
                        <id>process-aot</id>
                        <goals>
                            <goal>process-aot</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <configuration>
                    <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                    <metadataRepository>
                        <enabled>true</enabled>
                    </metadataRepository>
                    <requiredVersion>22.3</requiredVersion>
                </configuration>
                <executions>
                    <execution>
                        <id>add-reachability-metadata</id>
                        <goals>
                            <goal>add-reachability-metadata</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <!-- The native profile is already defined by the parent POM. -->
        <!-- To use this plugin, we need GraalVM (located under $GRAALVM_HOME) and -->
        <!-- native-builder (located in the $PATH) -->
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

And the 

databaseChangeLog:
  - include:
      file: db/changelog/changes/audit_log.sql

Error message while running the native image :

```
Caused by: liquibase.exception.ChangeLogParseException: Error parsing classpath:/db/changelog/db.changelog-master.yaml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:90)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:393)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:249)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2431)
	at liquibase.Liquibase.update(Liquibase.java:237)
	at liquibase.Liquibase.update(Liquibase.java:222)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:328)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:283)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747)
	... 18 common frames omitted
Caused by: liquibase.exception.SetupException: java.io.FileNotFoundException: The file db/changelog/changes/audit_log.sql was not found in the configured search path:
    - Spring classpath
More locations can be added with the 'searchPath' parameter.
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:447)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:376)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:84)
	... 32 common frames omitted
Caused by: liquibase.exception.ChangeLogParseException: java.io.FileNotFoundException: The file db/changelog/changes/audit_log.sql was not found in the configured search path:
    - Spring classpath
More locations can be added with the 'searchPath' parameter.
	at liquibase.parser.core.sql.SqlChangeLogParser.parse(SqlChangeLogParser.java:42)
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:775)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:438)
	... 34 common frames omitted
Caused by: java.io.FileNotFoundException: The file db/changelog/changes/audit_log.sql was not found in the configured search path:
    - Spring classpath
More locations can be added with the 'searchPath' parameter.
	at liquibase.resource.ResourceAccessor.getExisting(ResourceAccessor.java:162)
	at liquibase.parser.core.sql.SqlChangeLogParser.parse(SqlChangeLogParser.java:38)
	... 36 common frames omitted
```

I also tried with the below liquibase config:

databaseChangeLog:
  - includeAll:
      path: db/changelog/changes/

Seems no luck . This is the issue i got 

```
Caused by: liquibase.exception.ChangeLogParseException: Error parsing classpath:/db/changelog/db.changelog-master.yaml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:90)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:393)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:249)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2431)
	at liquibase.Liquibase.update(Liquibase.java:237)
	at liquibase.Liquibase.update(Liquibase.java:222)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:328)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:283)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747)
	... 18 common frames omitted
Caused by: liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'db/changelog/changes/'
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:688)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:490)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:376)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:84)
	... 32 common frames omitted
Caused by: liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'db/changelog/changes/'
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:678)
	... 35 common frames omitted
```

Thanks for your help :-)

**Comment by wilkinsona** [comment]
I don't think this has anything to do with the reachability metadata for Liquibase as the location of your changelog files and the files that they include is specific to your application. You'll need to configure Graal to include the resources in `db/changelog/changes/` in your native image.

**Comment by nkonev** [comment]
For the Spring Boot try the following (it's Kotlin, but it's easy to rewrite on Java)

```kotlin
@ImportRuntimeHints(LiquibaseRuntimeHints::class)
@SpringBootApplication
class YourApplication()

class LiquibaseRuntimeHints : RuntimeHintsRegistrar {

    override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
        hints.resources().registerPattern("db/changelog/changes/*.sql")
        hints.resources().registerPattern("db/changelog/db.changelog-master.yaml")
    }

}
```

**Comment by prabuanandan** [comment]
Thanks for your Answer. it really helps !!!! I rewrote the class as mentioned below

`


import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.RuntimeHintsRegistrar;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ImportRuntimeHints;

@SpringBootApplication
@ImportRuntimeHints(TestApplication.LiquibaseRuntimeHints.class)
public class TestApplication {

    public static void main(String[] args) {
        SpringApplication.run(TestApplication.class, args);
    }

    static class LiquibaseRuntimeHints implements RuntimeHintsRegistrar {


        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
            hints.resources().registerPattern("db/changelog/changes/*.sql");

        }
    }
}
`

**Comment by nkonev** [comment]
https://github.com/spring-projects/spring-boot/pull/34729
