### ISSUE TITLE
[QUESTION]java.lang.NoSuchMethodException: org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard.<init>() with GraalVM native-image

### ISSUE THREAD

**Issue by ideaviewes** [oracle/graalvm-reachability-metadata#302]
When you compile and run the application with GraalVM native-image the following error occurs:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': Default-resolver threw exception
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1156) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:931) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[kt.exe:6.0.9]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[kt.exe:3.1.0]
        at com.icodeview.kt.KtApplicationKt.main(KtApplication.kt:13) ~[kt.exe:na]
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Default-resolver threw exception
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:223) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:180) ~[na:na]
        at org.hibernate.boot.internal.MetadataBuilderImpl$MetadataBuildingOptionsImpl.<init>(MetadataBuilderImpl.java:750) ~[na:na]
        at org.hibernate.boot.internal.MetadataBuilderImpl.<init>(MetadataBuilderImpl.java:140) ~[na:na]
        at org.hibernate.boot.MetadataSources.getMetadataBuilder(MetadataSources.java:163) ~[na:na]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:269) ~[kt.exe:6.2.2.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:190) ~[kt.exe:6.2.2.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) ~[na:na]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[kt.exe:6.0.9]
        ... 16 common frames omitted
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Could not instantiate named strategy class [org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:244) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:180) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:167) ~[na:na]
        at org.hibernate.boot.internal.MetadataBuilderImpl$MetadataBuildingOptionsImpl$2.call(MetadataBuilderImpl.java:756) ~[na:na]
        at org.hibernate.boot.internal.MetadataBuilderImpl$MetadataBuildingOptionsImpl$2.call(MetadataBuilderImpl.java:753) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:220) ~[na:na]
        ... 29 common frames omitted
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Could not instantiate named strategy class [org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.lambda$static$0(StrategySelectorImpl.java:41) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:240) ~[na:na]
        ... 34 common frames omitted
Caused by: java.lang.InstantiationException: org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard
        at java.base@17.0.6/java.lang.Class.newInstance(DynamicHub.java:639) ~[kt.exe:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.lambda$static$0(StrategySelectorImpl.java:37) ~[na:na]
        ... 35 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard.<init>()
        at java.base@17.0.6/java.lang.Class.getConstructor0(DynamicHub.java:3585) ~[kt.exe:na]
        at java.base@17.0.6/java.lang.Class.newInstance(DynamicHub.java:626) ~[kt.exe:na]
        ... 36 common frames omitted
```

How to reproduce:
* git clone https://github.com/ideaviewes/ktlearn.git
* ./gradlew nativeCompile
* ./build/native/nativeCompile/kt.exe

**Comment by RMCampos** [comment]
👍🏻 +1 for me. I would like to understand more about this issue. Thanks.

**Comment by guillaume-viland** [comment]
Hello +1 for me, thank you to keep me posted

**Comment by ironman19933** [comment]
+1 for me as well. I have been facing the same issue and unable to resolve it.

**Comment by ideaviewes** [comment]
1、build a jar gradlew bootjar 
2、java -agentlib:native-image-agent=config-output-dir=META-INF/native-image -jar .\build\libs\kt-0.0.1-SNAPSHOT.jar
3、ctrl+c， will generate META-INF directory，copy the directory to /src/main/resources
4、gradelw nativeComiple
5、./build/native/nativeCompile/kt.exe，got another exception
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': No classes have been predefined during the image build to load from bytecodes at runtime.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1156) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:931) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[kt.exe:6.0.9]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[kt.exe:3.1.0]
        at com.icodeview.kt.KtApplicationKt.main(KtApplication.kt:12) ~[kt.exe:na]
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130) ~[na:na]
        at java.base@17.0.6/java.lang.ClassLoader.defineClass(ClassLoader.java:294) ~[kt.exe:na]
        at net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1383) ~[na:na]        at net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:459) ~[na:na]
        at net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:452) ~[na:na]
        at java.base@17.0.6/java.security.AccessController.executePrivileged(AccessController.java:168) ~[kt.exe:na]
        at java.base@17.0.6/java.security.AccessController.doPrivileged(AccessController.java:318) ~[kt.exe:na]
        at net.bytebuddy.utility.dispatcher.JavaDispatcher.doPrivileged(JavaDispatcher.java) ~[na:na]
        at net.bytebuddy.utility.dispatcher.JavaDispatcher.<clinit>(JavaDispatcher.java:87) ~[na:na]
        at net.bytebuddy.description.type.TypeDescription$ForLoadedType.<clinit>(TypeDescription.java:8659) ~[na:na]
        at net.bytebuddy.matcher.ElementMatchers.isFinalizer(ElementMatchers.java:1624) ~[na:na]
        at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState$ProxyDefinitionHelpers.<init>(ByteBuddyState.java:296) ~[na:na]
        at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.<clinit>(ByteBuddyState.java:71) ~[na:na]
        at org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl.<init>(BytecodeProviderImpl.java:123) ~[kt.exe:6.2.2.Final]
        at org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl.<init>(BytecodeProviderImpl.java:115) ~[kt.exe:6.2.2.Final]
        at org.hibernate.bytecode.internal.BytecodeProviderInitiator.buildBytecodeProvider(BytecodeProviderInitiator.java:59) ~[na:na]
        at org.hibernate.bytecode.internal.BytecodeProviderInitiator.buildDefaultBytecodeProvider(BytecodeProviderInitiator.java:46) ~[na:na]
        at org.hibernate.jpa.internal.enhance.EnhancingClassTransformerImpl.<init>(EnhancingClassTransformerImpl.java:34) ~[na:na]
        at org.hibernate.jpa.boot.internal.PersistenceUnitInfoDescriptor.pushClassTransformer(PersistenceUnitInfoDescriptor.java:113) ~[kt.exe:6.2.2.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:340) ~[kt.exe:6.2.2.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:190) ~[kt.exe:6.2.2.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) ~[na:na]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[kt.exe:6.0.9]
        ... 16 common frames omitted
```

**Comment by shirohoo** [comment]
+1

**Comment by wilkinsona** [comment]
@ideaviewes There should be no need to use the agent and the second error sounds like you haven't configured Hibernate's enhancer build plugin.

**Comment by ideaviewes** [comment]
@wilkinsona ,thank you,it works!
