### ISSUE TITLE
Add support for Flyway

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graalvm-reachability-metadata#39]
We use `org.flywaydb:flyway-core:9.0.1` and it doesn't work in native-image:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer': null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1754) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:931) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:926) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:592) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[flyway:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:430) ~[flyway:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[flyway:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[flyway:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[flyway:3.0.0-SNAPSHOT]
	at com.example.flyway.FlywayApplication.main(FlywayApplication.java:10) ~[flyway:na]
Caused by: java.lang.ExceptionInInitializerError: null
	at org.flywaydb.core.api.logging.LogFactory.autoDetectLogCreator(LogFactory.java:129) ~[na:na]
	at org.flywaydb.core.api.logging.LogFactory.getLogCreator(LogFactory.java:104) ~[na:na]
	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:86) ~[na:na]
	at org.flywaydb.core.internal.license.VersionPrinter.<clinit>(VersionPrinter.java:27) ~[na:na]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:121) ~[flyway:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:126) ~[flyway:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[flyway:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1800) ~[flyway:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1750) ~[flyway:6.0.0-SNAPSHOT]
	... 17 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate class org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator : org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:50) ~[na:na]
	at org.flywaydb.core.api.logging.LogFactory.autoDetectLogCreator(LogFactory.java:134) ~[na:na]
	at org.flywaydb.core.api.logging.LogFactory.getLogCreator(LogFactory.java:104) ~[na:na]
	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:86) ~[na:na]
	at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:20) ~[na:na]
	... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.internal.logging.log4j2.Log4j2LogCreator
	at java.lang.Class.forName(DynamicHub.java:1136) ~[flyway:na]
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:48) ~[na:na]
	... 30 common frames omitted
```

**Comment by mhalbritter** [comment]
I'm starting to work on that one.
