### ISSUE TITLE
Update existing library: org.flywaydb:flyway-core:10.0.0

### ISSUE THREAD

**Issue by wetted** [oracle/graalvm-reachability-metadata#424]
**Is your feature request related to a problem? Please describe.**

The graalvm-reachability-metadata supports `org.flywaydb 9.0.1`, but is broken for flyway 10.0.0
https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/org.flywaydb/flyway-core

**Describe the solution you'd like**

- add support for `org.flywaydb:flyway-core:10.0.0`
- add support for `org.flywaydb:flyway-sqlserver:10.0.0`
- add support for `org.flywaydb:flyway-database-oracle:10.0.0`
- add support for `org.flywaydb:flyway-database-postgresql:10.0.0`

**Describe alternatives you've considered**

- null

**Additional context**

`  | Caused by: org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively invoke method public java.lang.String org.flywaydb.core.internal.command.clean.CleanModeConfigurationExtension.getNamespace() without it being registered for runtime reflection. Add public java.lang.String org.flywaydb.core.internal.command.clean.CleanModeConfigurationExtension.getNamespace() to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help. |  
`
https://github.com/micronaut-projects/micronaut-flyway/actions/runs/6935025730/job/18864351069?pr=472

**Comment by mhalbritter** [comment]
Flyway fails with Spring Boot 3.4.0-M2:

```
Caused by: org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively invoke method public boolean org.flywaydb.core.internal.publishing.PublishingConfigurationExtension.isPublishResult() without it being registered for runtime reflection. Add public boolean org.flywaydb.core.internal.publishing.PublishingConfigurationExtension.isPublishResult() to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.MissingReflectionRegistrationUtils.forQueriedOnlyExecutable(MissingReflectionRegistrationUtils.java:72)
at java.base@21.0.3/java.lang.reflect.Method.acquireMethodAccessor(Method.java:77)
```

**Comment by mhalbritter** [comment]
I've added metadata for Flyway 10.17.1 in #531.

**Comment by asm0dey** [comment]
With `10.20.1` and spring `3.4.0` it fails with 

```
The program tried to reflectively invoke method

   public java.lang.String org.flywaydb.core.internal.configuration.extensions.DeployScriptFilenameConfigurationExtension.getScriptFilename()

 without it being registered for runtime reflection.
```

**Comment by mhalbritter** [comment]
This can be fixed by using the latest version of the reachability metadata:

```gradle
graalvmNative {
	metadataRepository {
		version = '0.3.15'
	}
}
```

or

```xml
<plugin>
	<groupId>org.graalvm.buildtools</groupId>
	<artifactId>native-maven-plugin</artifactId>
	<configuration>
		<metadataRepository>
			<version>0.3.15</version>
		</metadataRepository>
	</configuration>
</plugin>
```

Spring Boot 3.4.1 will use the latest Native Build Tools release, which includes this reachability metadata version by default.

**Comment by msosa** [comment]
Upgrading to Spring Boot 3.4.1 did not seem to fix it for me. The location of my error seems a little different than the others I see here though:
```
Caused by: org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively invoke method public boolean org.flywaydb.core.internal.publishing.PublishingConfigurationExtension.isCheckDriftOnMigrate() without it being registered for runtime reflection.
```

**Comment by mhalbritter** [comment]
> Spring Boot 3.4.1 will use the latest Native Build Tools release, which includes this reachability metadata version by default.

This isn't true, sorry!

Spring Boot 3.4.1 uses Native Build Tools [0.10.4](https://github.com/graalvm/native-build-tools/releases/tag/0.10.4), which uses the [0.3.14 metadata](https://github.com/graalvm/native-build-tools/pull/640/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR4).

So the workaround from https://github.com/oracle/graalvm-reachability-metadata/issues/424#issuecomment-2522330577 still applies to Spring Boot 3.4.1.

**Comment by goafabric** [comment]
I am having the same problem since boot 3.4x with PublishingConfigurationExtension,
and also since 3.3 there is a similar problem with "TransactionalModel" if flyway is combined with Hibernate.

The following Spring annotations would fix it, i think this could be easily translated to graalvm defaults.
And I understand the workaround that Moritz mentioned concerning the first issue.

@RegisterReflection(classes = {org.flywaydb.core.internal.publishing.PublishingConfigurationExtension.class, org.flywaydb.database.postgresql.TransactionalModel.class}, memberCategories = {MemberCategory.INVOKE_PUBLIC_METHODS, MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS})

**Comment by goafabric** [comment]
@joshlong 
Nope, just verified with Boot 3.5.3 and buildtools.native 0.10.6
When removing the hints i mentioned previously it will still crash

Caused by: org.flywaydb.core.api.FlywayException: No serializer found for class org.flywaydb.database.postgresql.TransactionalModel and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS). This appears to be a native image, in which case you may need to configure reflection for the class that is to be serialized (through reference chain: org.flywaydb.database.postgresql.PostgreSQLConfigurationExtension["transactional"])

**Comment by vjovanov** [comment]
### Human intervention needed

The automated job failed for `org.flywaydb:flyway-core:10.0.0`.

Preserved work branch: https://github.com/oracle/graalvm-reachability-metadata/tree/ai%2Fvjovanov%2Fhuman-intervention%2Fissue-424-library-new-request-org.flywaydb-flyway-core-10.0.0-769da1bd

The most likely failing stage was test generation/result capture, not library validation itself. In `stats/org.flywaydb/flyway-core/10.0.0/execution-metrics.json`, the run is recorded as `status: failure` with `generated_loc: 0`, `metadata_entries: 0`, `test_file: None`, and `metadata_file: None`. The preserved branch still contains only the scaffold test `tests/src/org.flywaydb/flyway-core/10.0.0/src/test/java/org_flywaydb/flyway_core/Flyway_coreTest.java`, which still prints `This is just a placeholder, implement your test`, and the Gradle log shows that placeholder test is what actually ran successfully.

The generation transcript shows the agent did draft a real `ClassUtilsTest.java` and reported it as an untracked file, but that file was never preserved into the branch, so the generated test work was effectively lost. See `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/add-new-library-support/pi-generation-2026-05-03T00-06-07-548504Z.log`, `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/gradle-test/gradle-test-2026-05-03T00-06-07-557280Z.log`, and `stats/org.flywaydb/flyway-core/10.0.0/execution-metrics.json`. There was also a later downstream native verification failure: `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/native-test-verify/cycle-0-runNativeTraceImage-2026-05-03T00-06-57-420040Z.log` shows `MissingResourceRegistrationError` for `META-INF/services/org.junit.platform.launcher.PostDiscoveryFilter`. The reported dynamic-access coverage is only 18/40 (45.00%), which is below the 50% floor for a `library-new-request`.

Recommended manual next steps:
1. Recover or recreate the intended library-specific Flyway tests from the generation transcript and commit them under `tests/src/org.flywaydb/flyway-core/10.0.0/`, replacing the scaffold placeholder.
2. Rerun `./gradlew test -Pcoordinates=org.flywaydb:flyway-core:10.0.0` and confirm dynamic-access coverage improves past 50%.
3. If native verification still fails, add the missing resource registration for `META-INF/services/org.junit.platform.launcher.PostDiscoveryFilter` and rerun native trace verification.

**Comment by vjovanov** [comment]
Human intervention needed

The automated job for `org.flywaydb:flyway-core:10.0.0` failed. Preserved work branch: https://github.com/oracle/graalvm-reachability-metadata/tree/ai%2Fvjovanov%2Fhuman-intervention%2Fissue-424-library-new-request-org.flywaydb-flyway-core-10.0.0-2f3aa381

Most likely failure stage: `add-new-library-support` / test-generation persistence. The preserved tree still contains only the placeholder test at `tests/src/org.flywaydb/flyway-core/10.0.0/src/test/java/org_flywaydb/flyway_core/Flyway_coreTest.java`, while `stats/org.flywaydb/flyway-core/10.0.0/execution-metrics.json` reports `status: failure`, `generated_loc: 0`, `artifacts.test_file: None`, `artifacts.metadata_file: None`, and the starting/ending commit are identical. At the same time, the generation log shows a proposed `ClassUtilsTest`, and the build outputs prove that transient test actually ran: `tests/src/org.flywaydb/flyway-core/10.0.0/build/test-results/test/TEST-org_flywaydb.flyway_core.ClassUtilsTest.xml` has 9 passing tests, and `tests/src/org.flywaydb/flyway-core/10.0.0/build/reports/dynamic-access/dynamic-access-coverage.json` shows `ClassUtils` reached `18/18`, but overall dynamic-access coverage is only `18/40` (45%), below the new-library 50% gate.

Please inspect:
- `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/add-new-library-support/pi-generation-2026-05-03T05-31-30-594746Z.log`
- `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/gradle-test/gradle-test-2026-05-03T05-31-30-604905Z.log`
- `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/native-test-verify/cycle-0-runNativeTraceImage-2026-05-03T05-32-08-371023Z.log`

Manual next steps:
1. Recover the generated `ClassUtilsTest` from the generation log/build outputs into `tests/src/org.flywaydb/flyway-core/10.0.0/src/test/java/...` and replace the placeholder `Flyway_coreTest`.
2. Extend the tests to cover at least one additional uncovered path beyond `ClassUtils` (for example `ClassicConfiguration`, `MergeUtils`, or the resource-loading paths) so dynamic-access coverage exceeds 50%.
3. Re-run `./gradlew test -Pcoordinates=org.flywaydb:flyway-core:10.0.0` and confirm the updated result in `tests/src/org.flywaydb/flyway-core/10.0.0/build/reports/dynamic-access/dynamic-access-coverage.json`.

**Comment by vjovanov** [comment]
Human intervention needed

The automated job failed for `org.flywaydb:flyway-core:10.0.0`. Preserved work branch: https://github.com/oracle/graalvm-reachability-metadata/tree/ai%2Fvjovanov%2Fhuman-intervention%2Fissue-424-library-update-request-org.flywaydb-flyway-core-10.0.0-f785464e

Most likely failing stage: generated test execution during `gradle-test` / `:nativeTest`. In `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/gradle-test/gradle-test-2026-05-03T05-31-30-604905Z.log`, the generated `org_flywaydb.flyway_core.ClassUtilsTest` runs under Native Image and `instantiatesClassByNameWithExpressionConstructorPath()` fails with `org.flywaydb.core.api.FlywayException: Unable to instantiate class org_flywaydb.flyway_core.ClassUtilsTest$DefaultConstructible`, caused by `java.lang.NoSuchMethodException: <unbound>=Class.new();`. That log ends with `9 tests successful`, `1 tests failed`, and `BUILD FAILED`. The trace-image build itself succeeds in `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/native-test-verify/cycle-0-runNativeTraceImage-2026-05-03T05-32-08-371023Z.log`, so this looks like a bad generated test rather than a native-image build failure.

There is also a persistence inconsistency worth checking. `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/add-new-library-support/pi-generation-2026-05-03T05-31-30-594746Z.log` shows the generator proposing a new `ClassUtilsTest`, but `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/failure-analysis/codex_failure_analysis_issue_424.log` records that the preserved tree still only had the placeholder `Flyway_coreTest`, with `status: failure`, `generated_loc: 0`, `test_file: None`, and `metadata_file: None`. That suggests the generated test either was not persisted cleanly or was discarded after the failing run.

Please inspect:
- `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/gradle-test/gradle-test-2026-05-03T05-31-30-604905Z.log`
- `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/add-new-library-support/pi-generation-2026-05-03T05-31-30-594746Z.log`
- `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/native-test-verify/cycle-0-runNativeTraceImage-2026-05-03T05-32-08-371023Z.log`
- `human-intervention-logs/org.flywaydb:flyway-core:10.0.0/failure-analysis/codex_failure_analysis_issue_424.log`

1. Recover or recreate `ClassUtilsTest` in `tests/src/org.flywaydb/flyway-core/10.0.0/src/test/java/...` so the preserved branch contains the actual generated test instead of only the placeholder scaffold.
2. Fix or remove `instantiatesClassByNameWithExpressionConstructorPath()` so it matches `ClassUtils.instantiate` behavior, then rerun `./gradlew test -Pcoordinates=org.flywaydb:flyway-core:10.0.0`.
3. After the test passes, re-check dynamic-access coverage and add coverage beyond `ClassUtils` if needed before resuming automation.

**Comment by vjovanov** [comment]
Human intervention needed

The automated `library-update-request` job failed for `org.flywaydb:flyway-core:10.0.0`. Preserved work branch: https://github.com/oracle/graalvm-reachability-metadata/tree/ai%2Fvjovanov%2Fhuman-intervention%2Fissue-424-library-update-request-org.flywaydb-flyway-core-10.0.0-9987b56e

The most likely failure was the test-generation/setup stage, before any generated metadata or metrics were written. Evidence: there is no `tests/src/org.flywaydb/flyway-core/10.0.0/`, no `metadata/org.flywaydb/flyway-core/10.0.0/`, no `stats/org.flywaydb/flyway-core/10.0.0/`, and no run metrics file for this run. `metadata/org.flywaydb/flyway-core/index.json` already has a `default-for` entry that covers `10.0.x` through `10.14.x` via metadata version `10.10.0`, but `forge/utility_scripts/metadata_index.py` only resolves test directories from exact `tested-versions` / exact `metadata-version` matches, so the workflow falls back to the nonexistent `tests/src/org.flywaydb/flyway-core/10.0.0/`. `forge/ai_workflows/improve_library_coverage.py` exits immediately when that directory does not exist.

Logs to inspect: `forge/logs/org.flywaydb:flyway-core:10.0.0/failure-analysis/codex_failure_analysis_issue_424.log`. I did not find any preserved generation or Gradle logs under `forge/logs/org.flywaydb:flyway-core:10.0.0/`, and no scratch metrics artifacts were available for this run.

1. Decide whether `10.0.0` should reuse the existing `10.10.0` Flyway test/metadata setup; if yes, add `10.0.0` to the relevant `tested-versions` entry in `metadata/org.flywaydb/flyway-core/index.json` or update the resolver to honor `default-for`.
2. If `10.0.0` needs its own test project, scaffold `tests/src/org.flywaydb/flyway-core/10.0.0/` from `tests/src/org.flywaydb/flyway-core/10.10.0/` and rerun the workflow.
3. Re-run with generation/Gradle logs preserved so the next failure leaves actionable diagnostics.

**Comment by jvukicev** [comment]
Apologies for the delay on this library update request.

The `library-update-request` automation is currently not working correctly, which has delayed processing these issues. We are working on fixing it and expect to have the automation back in shape within the next couple of days.

Thank you for your patience.

**Comment by jvukicev** [comment]
Based on the discussion above, and merged related PRs, I'm closing this as `Done`. If the issue persists feel free to reopen the issue or create a new one with the detailed error.
