### ISSUE TITLE
Update existing library: com.github.ben-manes.caffeine:caffeine:3.1.8

### ISSUE THREAD

**Issue by sleicht** [oracle/graalvm-reachability-metadata#436]
Hello! I use spring boot (v. 3.2.1) with `com.github.ben-manes.caffeine` (v. 3.1.8). When I make native-image with default configuration of CaffeineCacheManager, I get this error:

```
Caused by: java.lang.IllegalStateException: SSSW
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newFactory(LocalCacheFactory.java:114) ~[microservice:3.1.8]
        at java.base@21.0.1/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[microservice:na]
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:97) ~[microservice:3.1.8]
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:46) ~[microservice:3.1.8]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3953) ~[microservice:3.1.8]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.<init>(BoundedLocalCache.java:4451) ~[na:na]
        at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1073) ~[microservice:3.1.8]
        at com.COMPANY.libraries.auth.service.KeycloakService.<init>(KeycloakService.java:72) ~[microservice:na]
        at com.COMPANY.libraries.auth.service.KeycloakService__BeanDefinitions.lambda$getKeycloakServiceInstanceSupplier$0(KeycloakService__BeanDefinitions.java:19) ~[na:na]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[microservice:6.1.2]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[microservice:6.1.2]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:206) ~[na:na]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58) ~[microservice:6.1.2]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46) ~[microservice:6.1.2]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:214) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:206) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:949) ~[microservice:6.1.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1216) ~[microservice:6.1.2]
        ... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSSW
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:122) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:86) ~[na:na]
        at java.base@21.0.1/java.lang.Class.forName(DynamicHub.java:1346) ~[microservice:na]
        at java.base@21.0.1/java.lang.Class.forName(DynamicHub.java:1335) ~[microservice:na]
        at java.base@21.0.1/java.lang.invoke.MethodHandles$Lookup.findClass(MethodHandles.java:2869) ~[microservice:na]
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newFactory(LocalCacheFactory.java:104) ~[microservice:3.1.8]
        ... 35 common frames omitted
```

I found similar problem [here](https://github.com/oracle/graalvm-reachability-metadata/issues/271)

If I understand this repo correct, it misses the [metadata for Caffeine](https://github.com/oracle/graalvm-reachability-metadata/blob/master/metadata/com.github.ben-manes.caffeine/caffeine/3.1.2/reflect-config.json) for version 3.1.8 and it misses class `com.github.benmanes.caffeine.cache.SSSW`

The application starts if I add following hint manually:

```java
hints.reflection().registerType(
    TypeReference.of("com.github.benmanes.caffeine.cache.SSSW"),
    MemberCategory.PUBLIC_FIELDS, MemberCategory.INVOKE_DECLARED_CONSTRUCTORS, MemberCategory.INVOKE_PUBLIC_METHODS
```

This additional `CaffeineTest` leads to the same exception:
```java
    @Test
    void testRecordStats() {
        LoadingCache<String, String> cache = Caffeine.newBuilder()
            .expireAfterWrite(Duration.ofMinutes(20))
            .recordStats()
            .build(key -> key.equals("Hello") ? "World" : "Universe");
        assertThat(cache.get("Hello")).isEqualTo("World");
        assertThat(cache.getAll(List.of("Hi", "Aloha"))).isEqualTo(Map.of("Hi", "Universe", "Aloha", "Universe"));
    }
```

**Comment by sleicht** [comment]
Therefore missing in `reflect-config.json`:

```json

  {
    "condition": {
      "typeReachable": "com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache"
    },
    "name": "com.github.benmanes.caffeine.cache.SSSW",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [
          "com.github.benmanes.caffeine.cache.Caffeine",
          "com.github.benmanes.caffeine.cache.AsyncCacheLoader",
          "boolean"
        ]
      }
    ]
  }
```

**Comment by bpfoster** [comment]
`SSW` is not the only class, I received the same error on `com.github.benmanes.caffeine.cache.SSMSA`.  I bet there are a ton of classes to include here as Caffeine is building the class name [dynamically](https://github.com/ben-manes/caffeine/blob/b100cb9bf01269fbd46e5eac7fabf5db2ceedd58/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java#L56-L92) based on cache parameters.

**Comment by ben-manes** [comment]
@bpfoster yeah, pre-AOT this was a neat trick because it unloaded classes are basically free (just a little extra disk space). Thus, we could code generate the cache and the entry classes to minimize the memory footprint, e.g. only include the expiration timestamp if used. Using reflection avoids bloating the constant pool with a static mapping and that factory is cached making the cost a one-time class load followed by a map lookup and direct call to the constructor. All extremely cheap, hidden, classic JVM dynamism except now AOT peeks into the implementation and exposes this magic. There's not much we can do since it is breaking encapsulation and including all classes would bloat your native binary. I'm curious to see how Project Leyden will address this, as it might allow AOT for the main parts while not throwing out the JIT for dynamic parts.

You can try this [example](https://github.com/ben-manes/caffeine/tree/master/examples/graal-native) if you want to use the agent to discover the classes (it will output the `reflect-config.json` which you can copy into your project).

**Comment by kimeta** [comment]
Human intervention needed

The automated `library-update-request` job for `com.github.ben-manes.caffeine:caffeine:3.1.8` failed. Preserved work branch: https://github.com/oracle/graalvm-reachability-metadata/tree/ai%2Fkimeta%2Fhuman-intervention%2Fissue-436-library-update-request-com.github.ben-manes.caffeine-caffeine-3.1.8-b3d5bcc1

The most likely failing stage was test generation / coverage-improvement setup, before any useful Gradle run artifacts were preserved. Concrete evidence: the preserved branch is tree-identical to `origin/master` (no diff at all), there is no `human-intervention-logs/...` commit for this issue, there are no generated `3.1.8` entries under `tests/src/com.github.ben-manes.caffeine/caffeine/`, `metadata/com.github.ben-manes.caffeine/caffeine/`, or `stats/com.github.ben-manes.caffeine/caffeine/`, and there are no run metrics for this coordinate under `forge/benchmark_run_metrics/` or `forge/script_run_metrics/`. Also, `metadata/com.github.ben-manes.caffeine/caffeine/index.json` already lists `3.1.8` in `tested-versions` under metadata version `3.1.2`, and the reusable test project already exists under `tests/src/com.github.ben-manes.caffeine/caffeine/3.1.2/`, so this appears to be a redundant update attempt rather than a missing-support case.

Paths to inspect:
- `forge/logs/com.github.ben-manes.caffeine:caffeine:3.1.8/failure-analysis/`
- `forge/logs/com.github.ben-manes.caffeine:caffeine:3.1.8/failure-analysis/codex_failure_analysis_issue_436.log`
- `metadata/com.github.ben-manes.caffeine/caffeine/index.json`

Manual next steps:
1. Confirm whether issue `#436` should be closed as already supported/no-op, since `3.1.8` is already listed as tested.
2. If revalidation is still desired, run `./gradlew checkMetadataFiles -Pcoordinates=com.github.ben-manes.caffeine:caffeine:3.1.8` and `./gradlew test -Pcoordinates=com.github.ben-manes.caffeine:caffeine:3.1.8`.
3. Inspect the automation that created this `library-update-request` and why it reported `test_generation_failed` without preserving Gradle logs or metrics.

**Comment by jvukicev** [comment]
Apologies for the delay on this library update request.

The `library-update-request` automation is currently not working correctly, which has delayed processing these issues. We are working on fixing it and expect to have the automation back in shape within the next couple of days.

Thank you for your patience.
