### ISSUE TITLE
How to support float[].class in file: serialization-config.json

### ISSUE THREAD

**Issue by imgoby** [oracle/graalvm-reachability-metadata#459]
How to support float[].class in file: serialization-config.json?
1.
```
[
  {
    "name": "[F"
  }
]
```

2.
```
[
  {
    "name": "float[]"
  }
]
```

3.
```
[
  {
    "name": "java.lang.Float[]"
  }
]
```

no whether how to config,the exception is the same:

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: [F (targetConstructorClass: java.lang.Object). Usually adding [F to serialization-config.json fixes the problem.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:143)
	at java.base@17.0.5/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:48)
	at java.base@17.0.5/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:463)
	at java.base@17.0.5/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:376)
	at jdk.unsupported@17.0.5/sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:100)

```
wi

**Comment by vjovanov** [comment]
```
{ "name":"float[]" },
```
should work. Which GraalVM version are you using?

**Comment by imgoby** [comment]
17.0.10-graal
I install jdk by sdkman : sdk install java 17.0.10-graal
