### ISSUE TITLE
[QUESTION] Add support  for  [com.dameng::DmjdbcDriver17:8.1.3.140]

### ISSUE THREAD

**Issue by chenjinfeng0505** [oracle/graalvm-reachability-metadata#488]
Describe the problem：

After compiling with native image,  it failed to connect dameng client.  The error message is as follows:

2024-04-25 10:44:22.200  INFO [http-nio-13000-exec-3] [c.h.h.c.exception.GlobalExceptionAdvice ] - into global Exception: e=jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoClassDefFoundError: Could not initialize class dm.jdbc.driver.DBError
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1096)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at com.hisense.ram.filter.AuthFilter.doFilter(AuthFilter.java:105)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base@17.0.9/java.lang.Thread.run(Thread.java:842)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class dm.jdbc.driver.DBError
        at dm.jdbc.a.a.w.q(SourceFile:300)
        at dm.jdbc.a.a.w.p(SourceFile:1)
        at dm.jdbc.a.a.y.L(SourceFile:542)
        at dm.jdbc.a.a.a(SourceFile:269)
        at dm.jdbc.a.a.f(SourceFile:708)
        at dm.jdbc.a.a.e(SourceFile:684)
        at dm.jdbc.driver.DmdbConnection.openConnection(SourceFile:691)
        at dm.jdbc.internal.conf.EP.connect(SourceFile:143)
        at dm.jdbc.internal.conf.EPGroup$EPSelector.select(SourceFile:485)
        at dm.jdbc.internal.conf.EPGroup.connect(SourceFile:329)
        at dm.jdbc.driver.DmDriver.do_connect(SourceFile:164)
        at dm.jdbc.driver.DmDriver.connect(SourceFile:450)
        at java.sql@17.0.9/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql@17.0.9/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at com.hisense.historage.common.utils.sql.JdbcUtils.createConnection(JdbcUtils.java:27)
        at com.hisense.historage.dra.service.pi.converter.impl.DmEngineConverter.executeSql(DmEngineConverter.java:41)
        at com.hisense.historage.dra.service.pi.EngineService.executeCheckEngine(EngineService.java:175)
        at com.hisense.historage.dra.service.pi.EngineService.getRealEngine(EngineService.java:83)
        at com.hisense.historage.dra.service.pi.InstanceService.checkDBUserPrivilege(InstanceService.java:371)
        at com.hisense.historage.dra.controller.pi.InstanceManageController.checkDBUserPrivilege(InstanceManageController.java:263)
        at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
        at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:141)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.hisense.historage.common.base.aop.ControllerLogAspect.around(ControllerLogAspect.java:38)
        at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
        at com.hisense.historage.dra.controller.pi.InstanceManageController$$SpringCGLIB$$0.checkDBUserPrivilege(<generated>)
        at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
        ... 44 more

 If there is any good solution, please help synchronize it with us. 
 Thanks

**Comment by fniephaus** [comment]
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class dm.jdbc.driver.DBError
at dm.jdbc.a.a.w.q(SourceFile:300)
at dm.jdbc.a.a.w.p(SourceFile:1)
at dm.jdbc.a.a.y.L(SourceFile:542)
at dm.jdbc.a.a.a(SourceFile:269)
at dm.jdbc.a.a.f(SourceFile:708)
at dm.jdbc.a.a.e(SourceFile:684)
at dm.jdbc.driver.DmdbConnection.openConnection(SourceFile:691)
```

The applications fails to initialize a class in the database driver, probably accessed reflectively so it's likely missing reachability metadata. The stack trace also suggest that the driver is partly obfuscated which could also be causing this issue (e.g., in case `dm.jdbc.driver.DBError` was also renamed). Given this is all caused in code of the database driver, please reach out to the maintainers of the driver and ask them to provide support for GraalVM. They could do this by adding appropriate declarative reachability metadata to the driver's JARs or implement a [`Feature`](https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/hosted/Feature.html) that registers types for reflection etc dynamically at build time.
