### ISSUE TITLE
objectInputStream.readObject() issue with springboot 3.3.0 + graalvm22 as native image

### ISSUE THREAD

**Issue by KafkaProServerless** [oracle/graalvm-reachability-metadata#498]
Hello team,

I would like to reach out regarding a small issue.

I have a very simple piece of code in my springboot 3.3 application.

The piece of code is:

```
 private static Map<?, ?> getNormalizedMap(final String encoded) {
        try (var objectInputStream = new ObjectInputStream(new ByteArrayInputStream(Base64.getDecoder().decode(encoded)))) {
            return (Map<?, ?>) objectInputStream.readObject();
        } catch (IOException | ClassNotFoundException | IllegalArgumentException e) {
            LOGGER.error("encoded={}", encoded, e);
            return Map.of();
        }
    }
```

This code would run fine on non native image, battle tested in production.

Now, we successfully built a native image. 

However, at run time, we would get an issue saying we need to add this ```java.util.Collections$UnmodifiableMap``` in this file ```serialization-config.json```, for line: ```return (Map<?, ?>) objectInputStream.readObject();```

We followed the instructions, not knowing if the instructions were correct to begin with.

After following the instructions, we get this error message:

```
java.io.InvalidClassException: java.util.HashMap; local class incompatible: stream classdesc serialVersionUID = 362498820763181265, local class serialVersionUID = -3563561681480877083
        at java.base@22.0.1/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
        at java.base@22.0.1/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2063)
        at java.base@22.0.1/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1912)
        at java.base@22.0.1/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2237)
        at java.base@22.0.1/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1747)
        at java.base@22.0.1/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2603)
        at java.base@22.0.1/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2454)
        at java.base@22.0.1/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
        at java.base@22.0.1/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1747)
        at java.base@22.0.1/java.io.ObjectInputStream.readObject(ObjectInputStream.java:525)
        at java.base@22.0.1/java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
```

Therefore, I would like to reach out, asking for help on this issue which is happening only with native images.

How to make ```return (Map<?, ?>) objectInputStream.readObject();``` work with native image?

Here is the minimal reproducible springboot app:

I am using ubuntu 22.04.4 LTS

download graalissue.zip and unzip it
cd inside the folder graalissue (which is a very small one file springboot project)
just run mvn clean install and run the jar
at this point, make a http request, something like curl http://localhost:8080/graalissue
you should see this output: "It should be 41 here => 41"

Once done

1) please run ```mvn -Pnative spring-boot:build-image``` this would create the graalvm native image
2) If the image is successfully created, can you run ```docker tag docker.io/library/graalissue:0.0.1-SNAPSHOT graalissue:latest```
3) from there, just run ```docker run -p 8080:8080 graalissue:latest```
4) same curl again: ```curl http://localhost:8080/graalissue```
5) and you should see something in the log like:

```
java.io.InvalidClassException: java.util.HashMap; local class incompatible: stream classdesc serialVersionUID = 362498820763181265, local class serialVersionUID = -3563561681480877083
        at java.base@22.0.1/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
        at java.base@22.0.1/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2063)
        at java.base@22.0.1/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1912)
        at java.base@22.0.1/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2237)
        at java.base@22.0.1/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1747)
        at java.base@22.0.1/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2603)
        at java.base@22.0.1/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2454)
        at java.base@22.0.1/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
        at java.base@22.0.1/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1747)
        at java.base@22.0.1/java.io.ObjectInputStream.readObject(ObjectInputStream.java:525)
        at java.base@22.0.1/java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
```
[graalissue.zip](https://github.com/oracle/graalvm-reachability-metadata/files/15404576/graalissue.zip)

**Comment by vjovanov** [comment]
This ticket will be handled in the GraalVM repo: https://github.com/oracle/graal/issues/8929
